substitutions:
  device_slug: greenhouse-controller
  friendly_name: Greenhouse Controller
  project_name: wrightwells.greenhouse_controller
  project_version: "0.2.0"
  soil_moisture_adc_pin: GPIO1
  flow_sensor_pin: GPIO2
  reed_switch_pin: GPIO4
  dht_high_pin: GPIO21
  dht_low_pin: GPIO47
  ds18b20_pin: GPIO48

packages:
  common: !include device-common.yaml
  network_profile: !include packages/network-wifi.yaml
  diagnostics_profile: !include packages/diagnostics-wifi.yaml
